### PR TITLE
Make contributors on object detail page link to results page

### PR DESCRIPTION
**Pull request by samanehsan**
Make contributor names listed on an "object detail" page link to the search results page faceted by that user.

### CODE REVIEW

**Comment by caneruguz** [comment]
@samanehsan This is not likely in the scope of this fix but the contributor id's are used for the list facet. It shows the list but the id is no longer recognizable as a person. it's fine if that shows in the url as a parameter but the tag also shows the id. This is not ideal from a usability perspective. 

screen shot 2017-03-28 at 12 22 29 pm

**Comment by samanehsan** [comment]
@caneruguz, I noticed this as well and made a ticket for the issue: https://openscience.atlassian.net/browse/SIDASH-52

Besides that, is this good to merge?

**Comment by caneruguz** [comment]
@samanehsan Yes, it does work and the changes are good.

**Comment by samanehsan** [comment]
Thanks @caneruguz! :octocat:

**Pull request merged**
